version: 2.1

jobs:
  build:
    working_directory: ~/slovensko-digital/www.ecosystem

    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          CC_TEST_REPORTER_ID: bdda8062e987a067dcdfe953dbc12024acaeb7e4c621304b69ba725fb5470a3e
          PGHOST: localhost
          RAILS_ENV: test

      - image: circleci/postgres:12-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./test-reporter
      - run: chmod +x ./test-reporter
      - restore_cache: { keys: ['{{ checksum "Gemfile.lock" }}'] }
      - run: gem update --system
      - run: gem install bundler
      - run: bundle config set deployment true
      - run: bundle install
      - save_cache: { key: '{{ checksum "Gemfile.lock" }}', paths: [vendor/bundle] }
      - run: dockerize -wait tcp://localhost:5432 -timeout 60s
      - run: bundle exec rake db:create db:structure:load --trace
      - run: ./test-reporter before-build
      - run: bundle exec rspec
      - run: ./test-reporter after-build --coverage-input-type simplecov --exit-code $?
