service:
  externalPort: 5000
  internalPort: 5000
image:
  secrets:
  - name: skdigital-bonet-registry
livenessProbe.initialDelaySeconds: 20
readinessProbe.initialDelaySeconds: 20 
application.migrateCommand: ["bundle", "exec", "rails", "db:migrate"]
